### ISSUE TITLE
Build a todo list

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#380]
**User stories**

- [x]  Store todo items

- [x]  Display todo items

- [x]  Add new todo items

- [x]  Change todo items

- [x]  Delete todo items

**Comment by LaievskyiSasha** [comment]
```
let list = []
console.log(list)
list.push('cat')
list.push('food')
list.push('milk')
list[list.indexOf('cat')] = 'dog'
list.splice(0,1)
console.log(list)
```

**Comment by Deobp** [comment]
`let todoList = ['we love JS'];
`

**Comment by Deobp** [comment]
`console.log(todoList);
`

**Comment by Deobp** [comment]
```
todoList.push('buy boat');
todoList.push('party on boat');
```

**Comment by Deobp** [comment]
```
todoList[0] = 'practice JS';
```

**Comment by Deobp** [comment]
```
// delete first element of todoList
todoList.slice(0,1);
```
