### ISSUE TITLE
Build a todo list using function

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#381]
**User stories**

- [x]  be able to display all todo list items

- [x]  be able to add an item to the todo list

- [x]  be able to modify a certain item in the todo list

- [x]  be able to delete a certain item in the todo list

**Comment by Deobp** [comment]
```
let todoList = ['milk', 'bread', 'vodka', 'boat'];
function display(){
    return `Your todo list: ${todoList}`;
}

```

**Comment by Deobp** [comment]
```
function addItem(item){
    todoList.push(item);
    return display();
}
```

**Comment by Deobp** [comment]
```
function modifyItem(position,value){
    todoList[position] = value;
    return display();
}
```

**Comment by Deobp** [comment]
```
function deleteItem(position){
    todoList.splice(position,1);
    return display();
}
```
