### ISSUE TITLE
Build a todo list using an object

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#384]
- [x]  store the todos array on an object

- [x]  have a displayTodos method

- [x]  have an addTodo method

- [x]  have a changeTodo method

- [x]  have a deleteTodo method

**Comment by Deobp** [comment]
```
let todoApp ={
    todo: ['vokda','hleb','eggs'],
    displayTodos: function(){
        console.log(`My todos: ${this.todo}`)
    },
    addTodo: function(item){
        this.todo.push(item);
        this.displayTodos();
    },
    changeTodo: function(index,value){
        this.todo[index] = value;
        this.displayTodos();
    },
    deleteTodo: function(index){
        this.todo.splice(index,1);
        this.displayTodos();
    },
    deleteAllTodos: function(){
        this.todo = [];
        this.displayTodos();
    }
};

```
