### ISSUE TITLE
Improve the todo list you have built using an object

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#385]
- [x]  addTodo should add objects

- [x]  changeTodo should change the todoText property

- [x]  toggleCompleted should change the completed property

**Comment by Deobp** [comment]
```

let todoApp ={
    todo: [],
    displayTodos: function(){
        console.log(`My todos: ${this.todo}`)
    },
    addTodo: function(todoText){
        this.todo.push({
            todoText : todoText, 
            completed : false,
        });
        this.displayTodos();
    },
    changeTodo: function(position, value){
        this.todo[position].todoText = value;
        this.displayTodos();
    },
    deleteTodo: function(index){
        this.todo.splice(index,1);
        this.displayTodos();
    },
    deleteAllTodos: function(){
        this.todo = [];
        this.displayTodos();
    },
    toggleCompleted: function(position){
       let todo = this.todo[position];
       todo.completed = !todo.completed;
    },
};
```
