### ISSUE TITLE
Improve todo list built with object

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#386]
- [x]  displayTodos should show todoText

- [x]  displayTodos should tell you if todo is empty

- [x]  displayTodos should show completed todos

**Comment by Deobp** [comment]
```
let todoApp ={
    todo: [],
    displayTodos: function(){
        if(this.todo.length == 0){
            console.log(`My todo is empty`);
        } else {
        console.log(`My todo items:`);
        for(let i = 0; i < this.todo.length; i++){
            console.log(this.todo[i].completed == true ? `(x) ${this.todo[i].todoText}` : `( ) ${this.todo[i].todoText}`);
        }
        }

    },
    addTodo: function(todoText){
        this.todo.push({
            todoText : todoText, 
            completed : false,
        });
        this.displayTodos();
    },
    changeTodo: function(position, value){
        this.todo[position].todoText = value;
        this.displayTodos();
    },
    deleteTodo: function(index){
        this.todo.splice(index,1);
        this.displayTodos();
    },
    deleteAllTodos: function(){
        this.todo = [];
        this.displayTodos();
    },
    toggleCompleted: function(position){
       let todo = this.todo[position];
       todo.completed = !todo.completed;
    },
};
```
